[[redirects]]
  from = "/guide"
  to = "https://docs.tresjs.org/guide"
  status = 301
  force = false
  query = {path = ":path"}
[build.environment]
  NODE_VERSION = "18"
[build]
  publish = "dist"
  command = "pnpm run build"
